import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Attendence Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<ClerkProvider>
    <html lang="en">
      <body>
        <SignedOut>
          
        </SignedOut>
        
        {children}
      </body>
    </html>
  </ClerkProvider>
  );
}
